workflows:
  build:
    name: Build App
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    trigger:
      branch: main
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - victor.galvez56@gmail.com
        notify:
          success: true
          failure: true
